<script setup>
// Edge DNS — zone detail. The resource-detail view for a single zone, in the
// persistent console shell (AppLayout: sidebar + GlobalHeader with the module
// breadcrumb — the /navigation skill). Its body is a full-bleed tab bar with two
// destinations:
//
//   Main Settings — the zone's configuration as ItemGroup sections (the /form
//                   Approach A: a section-titled flush CardBox whose body is an
//                   Item.List; Item.Title is the field label, the control lives in
//                   Item.Actions). Each EDITABLE group (General, Domain, DNSSEC,
//                   Status) owns its OWN footer Save and commits INDEPENDENTLY
//                   off its own flag + JSON baseline dirty check (the /form
//                   "ItemGroup with independent saves" pattern + /usability
//                   Pattern 1 lock). The nameservers and DNSSEC key values are
//                   read-only copy-out fields — an InputText + a copy IconButton
//                   as an InputGroup addon — so that section carries no Save.
//   Records       — a data-driven <Table> of the zone's DNS records with the
//                   tab's "Record" create action trailing on the tab bar; the
//                   Create Record drawer appends new rows.
//
// The active tab lives in the URL (?tab=) so it survives reload and is linkable.
import Button from "@aziontech/webkit/button";
import CardBox from "@aziontech/webkit/card-box";
import CopyButton from "@aziontech/webkit/copy-button";
import Dropdown from "@aziontech/webkit/dropdown";
import HelperText from "@aziontech/webkit/helper-text";
import IconButton from "@aziontech/webkit/icon-button";
import InputGroup from "@aziontech/webkit/input-group";
import InputText from "@aziontech/webkit/input-text";
import Item from "@aziontech/webkit/item";
import Switch from "@aziontech/webkit/switch";
import TabView from "@aziontech/webkit/tab-view";
import Table from "@aziontech/webkit/table";
import Tag from "@aziontech/webkit/tag";
import { toast } from "@aziontech/webkit/toast";
import { computed, reactive, ref } from "vue";
import { useRoute, useRouter } from "vue-router";

import { NAMESERVERS, policyLabel } from "../lib/edge-dns";
import CreateRecordDrawer from "./CreateRecordDrawer.vue";
import AppLayout from "./ui/AppLayout.vue";

const route = useRoute();
const router = useRouter();

// A tiny stand-in record — in a real app this comes from the route id.
const zone = {
  id: route.params.id || "6442",
  name: route.query.name || "test",
  domain: route.query.domain || "edgeflow.com",
};

const userEmail = computed(() => route.query.email || "myemail@azion.com");

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

// Active tab lives in the URL (?tab=) so it survives reload and is linkable.
const tabs = [
  { value: "main-settings", label: "Main Settings" },
  { value: "records", label: "Records" },
];
const activeTab = computed({
  get: () =>
    tabs.some((tab) => tab.value === route.query.tab) ? route.query.tab : "main-settings",
  set: (value) => router.replace({ query: { ...route.query, tab: value } }),
});

// ── Main Settings — independent saves per group ───────────────────────────
// Each editable group keeps its own reactive state + a JSON baseline; `*Dirty`
// is true only while the live values diverge from the saved baseline, so its
// footer Save stays disabled until the group is actually edited. Saving commits
// the new baseline, disabling Save again. The nameservers and DNSSEC key values
// are read-only, so they carry no state and no Save.
const errors = reactive({ name: "", domain: "" });

// Group 1 — General (Name).
const general = reactive({ name: zone.name });
const savingGeneral = ref(false);
const generalBaseline = ref(JSON.stringify(general));
const generalDirty = computed(() => JSON.stringify(general) !== generalBaseline.value);

// Group 2 — Domain (Domain Name).
const domainForm = reactive({ domain: zone.domain });
const savingDomain = ref(false);
const domainBaseline = ref(JSON.stringify(domainForm));
const domainDirty = computed(() => JSON.stringify(domainForm) !== domainBaseline.value);

// Group 3 — DNSSEC (enablement toggle; the key material below is read-only).
const dnssecForm = reactive({ enabled: true });
const savingDnssec = ref(false);
const dnssecBaseline = ref(JSON.stringify(dnssecForm));
const dnssecDirty = computed(() => JSON.stringify(dnssecForm) !== dnssecBaseline.value);

// DNSSEC key material — generated by Edge DNS, copied out to the domain provider.
const dnssec = {
  keyTag: "34505",
  algorithm: "13 (ECDSA Curve P-256 with SHA-256)",
  digestType: "2 (SHA-256)",
  digest: "8A9E1F2C3B4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F",
};

// Group 4 — Status (Active).
const statusForm = reactive({ active: true });
const savingStatus = ref(false);
const statusBaseline = ref(JSON.stringify(statusForm));
const statusDirty = computed(() => JSON.stringify(statusForm) !== statusBaseline.value);

// Shared independent-save helper: guard re-entrancy, validate (optional), lock
// off the group's flag, commit its baseline on success, release in finally.
const saveGroup = async (flag, message, commit, validateFn) => {
  if (flag.value) return; // per-group re-entrancy lock
  if (validateFn && !validateFn()) return;
  flag.value = true;
  try {
    await sleep(900);
    commit();
    toast.success(message);
  } catch (error) {
    toast.error("Could not save the settings.", {
      description: error?.message ?? "Check your connection and try again.",
    });
  } finally {
    flag.value = false; // release on success AND failure
  }
};

const saveGeneral = () =>
  saveGroup(
    savingGeneral,
    "General settings saved.",
    () => {
      generalBaseline.value = JSON.stringify(general);
    },
    () => {
      errors.name = general.name.trim() ? "" : "This field is required.";
      return !errors.name;
    },
  );

const saveDomain = () =>
  saveGroup(
    savingDomain,
    "Domain saved.",
    () => {
      domainBaseline.value = JSON.stringify(domainForm);
    },
    () => {
      errors.domain = domainForm.domain.trim() ? "" : "This field is required.";
      return !errors.domain;
    },
  );

const saveDnssec = () =>
  saveGroup(savingDnssec, "DNSSEC settings saved.", () => {
    dnssecBaseline.value = JSON.stringify(dnssecForm);
  });

const saveStatus = () =>
  saveGroup(savingStatus, "Status saved.", () => {
    statusBaseline.value = JSON.stringify(statusForm);
  });

// ── Records tab ───────────────────────────────────────────────────────────
const records = ref([
  {
    id: "423916",
    name: "sasas",
    type: "A",
    value: "192.0.2.1",
    ttl: 3600,
    policy: "simple",
    weight: 255,
    description: "TESDS",
  },
]);

const recordColumns = [
  { accessorKey: "name", header: "Name", enableSorting: true, principal: true },
  { accessorKey: "id", header: "ID", enableSorting: true },
  { accessorKey: "type", header: "Type", enableSorting: true },
  { accessorKey: "value", header: "Value", grow: 2 },
  { accessorKey: "ttl", header: "TTL (seconds)", enableSorting: true },
  { accessorKey: "policy", header: "Policy" },
  { accessorKey: "weight", header: "Weight" },
  { accessorKey: "description", header: "Description", grow: 2 },
  { id: "actions", kind: "action", hideable: false },
];

const recordDrawerOpen = ref(false);
const openRecordDrawer = () => {
  recordDrawerOpen.value = true;
};
const onRecordCreated = (record) => {
  records.value = [record, ...records.value];
};

const onRecordAction = (event, value, row) => {
  if (value === "delete") {
    records.value = records.value.filter((record) => record.id !== row.id);
    toast.success(`Record "${row.name}" deleted.`);
    return;
  }
  toast.info(`Editing ${row.name}`, { description: `Record ID ${row.id}` });
};
</script>

<template>
  <AppLayout
    active="edge-dns"
    :padded="false"
    :breadcrumb="[
      { label: 'Edge DNS', href: '/edge-dns' },
      { label: 'Zone', href: '/edge-dns' },
      { label: zone.name },
    ]"
  >
    <main class="flex h-full min-h-0 flex-col">
      <!-- Nav pattern (ApplicationDetail): the tabs are the full-bleed bottom of
           the header. The Records tab's "Record" create action trails on the same
           row; only the content below scrolls. -->
      <div class="border-b border-[var(--border-default)] px-[var(--spacing-md)]">
        <div class="flex items-end gap-[var(--spacing-sm)] py-[var(--spacing-sm)]">
          <TabView v-model:value="activeTab" class="min-w-0 flex-1">
            <TabView.List>
              <TabView.Item
                v-for="tab in tabs"
                :key="tab.value"
                :value="tab.value"
                :label="tab.label"
              />
            </TabView.List>
          </TabView>
          <Button
            v-if="activeTab === 'records'"
            label="Record"
            kind="primary"
            size="medium"
            icon="pi pi-plus"
            class="mb-[var(--spacing-xxs)] shrink-0"
            @click="openRecordDrawer"
          />
        </div>
      </div>

      <!-- Main Settings — ItemGroup sections, each editable group with its own
           independent Save. Only this region scrolls. -->
      <section
        v-if="activeTab === 'main-settings'"
        class="min-h-0 flex-1 overflow-auto p-[var(--spacing-md)]"
      >
        <div class="flex min-w-0 flex-col gap-[var(--spacing-lg)]">
          <!-- Group: General (own Save) -->
          <form
            class="flex flex-col gap-[var(--spacing-sm)]"
            aria-label="General settings"
            novalidate
            @submit.prevent="saveGeneral"
          >
            <p class="px-[var(--spacing-xs)] text-heading-xxs text-[var(--text-default)]">
              General
            </p>
            <CardBox :padded="false">
              <template #content>
                <fieldset
                  class="m-0 flex min-w-0 flex-col border-0 p-0"
                  :disabled="savingGeneral"
                >
                  <legend class="sr-only">General</legend>
                  <Item.List>
                    <Item size="small" class="items-start">
                      <Item.Content>
                        <Item.Title>Name</Item.Title>
                        <Item.Description>
                          Give a unique and descriptive name to identify your zone.
                        </Item.Description>
                      </Item.Content>
                      <Item.Actions class="flex-1 justify-end">
                        <div class="flex w-full max-w-[var(--container-sm)] flex-col gap-[var(--spacing-xs)]">
                          <InputText
                            v-model="general.name"
                            size="large"
                            class="w-full"
                            aria-label="Name"
                            :disabled="savingGeneral"
                            :required="!!errors.name"
                            :aria-describedby="errors.name ? 'zone-name-error' : undefined"
                            @update:model-value="errors.name = ''"
                          />
                          <HelperText
                            v-if="errors.name"
                            id="zone-name-error"
                            kind="required"
                            :label="errors.name"
                          />
                        </div>
                      </Item.Actions>
                    </Item>
                  </Item.List>
                </fieldset>
              </template>
              <template #footer>
                <div class="flex w-full items-center justify-end gap-[var(--spacing-sm)]">
                  <Button
                    label="Save"
                    kind="secondary"
                    size="medium"
                    :loading="savingGeneral"
                    :disabled="!generalDirty"
                    @click="saveGeneral"
                  />
                </div>
              </template>
            </CardBox>
          </form>

          <!-- Group: Domain (own Save) -->
          <form
            class="flex flex-col gap-[var(--spacing-sm)]"
            aria-label="Domain settings"
            novalidate
            @submit.prevent="saveDomain"
          >
            <p class="px-[var(--spacing-xs)] text-heading-xxs text-[var(--text-default)]">
              Domain
            </p>
            <CardBox :padded="false">
              <template #content>
                <fieldset
                  class="m-0 flex min-w-0 flex-col border-0 p-0"
                  :disabled="savingDomain"
                >
                  <legend class="sr-only">Domain</legend>
                  <Item.List>
                    <Item size="small" class="items-start">
                      <Item.Content>
                        <Item.Title>Domain Name</Item.Title>
                        <Item.Description>
                          Provide the domain name you want to host. Example:
                          mydomain.com.
                        </Item.Description>
                      </Item.Content>
                      <Item.Actions class="flex-1 justify-end">
                        <div class="flex w-full max-w-[var(--container-sm)] flex-col gap-[var(--spacing-xs)]">
                          <InputText
                            v-model="domainForm.domain"
                            size="large"
                            class="w-full"
                            aria-label="Domain Name"
                            :disabled="savingDomain"
                            :required="!!errors.domain"
                            :aria-describedby="errors.domain ? 'zone-domain-error' : undefined"
                            @update:model-value="errors.domain = ''"
                          />
                          <HelperText
                            v-if="errors.domain"
                            id="zone-domain-error"
                            kind="required"
                            :label="errors.domain"
                          />
                        </div>
                      </Item.Actions>
                    </Item>
                  </Item.List>
                </fieldset>
              </template>
              <template #footer>
                <div class="flex w-full items-center justify-end gap-[var(--spacing-sm)]">
                  <Button
                    label="Save"
                    kind="secondary"
                    size="medium"
                    :loading="savingDomain"
                    :disabled="!domainDirty"
                    @click="saveDomain"
                  />
                </div>
              </template>
            </CardBox>
          </form>

          <!-- Group: Configure your Nameserver (read-only copy-out — no Save).
               Each value is an InputText with a copy IconButton as an InputGroup
               addon. -->
          <section class="flex flex-col gap-[var(--spacing-sm)]">
            <p class="px-[var(--spacing-xs)] text-heading-xxs text-[var(--text-default)]">
              Configure your Nameserver
            </p>
            <CardBox :padded="false">
              <template #content>
                <Item.List>
                  <Item size="small" class="items-start">
                    <Item.Content>
                      <Item.Title>Nameservers</Item.Title>
                      <Item.Description>
                        Set Azion Edge DNS as the authoritative DNS server for a
                        domain by copying the nameservers values.
                      </Item.Description>
                    </Item.Content>
                    <Item.Actions class="flex-1 justify-end">
                      <div class="flex w-full max-w-[var(--container-sm)] flex-col gap-[var(--spacing-xs)]">
                        <InputGroup
                          v-for="(ns, index) in NAMESERVERS"
                          :key="ns"
                        >
                          <InputText
                            :model-value="ns"
                            size="large"
                            class="flex-1 font-code"
                            :aria-label="`Nameserver ${index + 1}`"
                            readonly
                          />
                          <CopyButton
                            kind="transparent"
                            :value="ns"
                            :aria-label="`Copy nameserver ${index + 1}`"
                          />
                        </InputGroup>
                        <HelperText label="Add the nameservers in your domain provider." />
                      </div>
                    </Item.Actions>
                  </Item>
                </Item.List>
              </template>
            </CardBox>
          </section>

          <!-- Group: DNSSEC (own Save on the enablement toggle; key material is
               read-only copy-out via InputGroup addons). -->
          <form
            class="flex flex-col gap-[var(--spacing-sm)]"
            aria-label="DNSSEC settings"
            novalidate
            @submit.prevent="saveDnssec"
          >
            <p class="px-[var(--spacing-xs)] text-heading-xxs text-[var(--text-default)]">
              DNSSEC
            </p>
            <CardBox :padded="false">
              <template #content>
                <fieldset
                  class="m-0 flex min-w-0 flex-col border-0 p-0"
                  :disabled="savingDnssec"
                >
                  <legend class="sr-only">DNSSEC</legend>
                  <Item.List>
                    <Item size="small" class="items-start">
                      <Item.Content>
                        <Item.Title>Enable DNSSEC</Item.Title>
                        <Item.Description>
                          Enable DNSSEC to secure your DNS zone against cache
                          poisoning and spoofing attacks. Configure the Key Tag and
                          Digest values in your domain provider to complete the
                          setup.
                        </Item.Description>
                      </Item.Content>
                      <Item.Actions class="flex-1 justify-end">
                        <Switch
                          v-model="dnssecForm.enabled"
                          aria-label="Enable DNSSEC"
                          :disabled="savingDnssec"
                        />
                      </Item.Actions>
                    </Item>

                    <template v-if="dnssecForm.enabled">
                      <Item size="small" class="items-start">
                        <Item.Content>
                          <Item.Title>Key Tag</Item.Title>
                          <Item.Description>
                            Unique identifier for the DNSSEC key used to sign your
                            zone. Use this value with your domain provider.
                          </Item.Description>
                        </Item.Content>
                        <Item.Actions class="flex-1 justify-end">
                          <InputGroup class="w-full max-w-[var(--container-sm)]">
                            <InputText
                              :model-value="dnssec.keyTag"
                              size="large"
                              class="flex-1 font-code"
                              aria-label="Key Tag"
                              readonly
                            />
                            <CopyButton
                              kind="transparent"
                              :value="dnssec.keyTag"
                              aria-label="Copy Key Tag"
                            />
                          </InputGroup>
                        </Item.Actions>
                      </Item>

                      <Item size="small" class="items-start">
                        <Item.Content>
                          <Item.Title>Algorithm</Item.Title>
                          <Item.Description>
                            Specifies the algorithm used to generate the DNSSEC key.
                          </Item.Description>
                        </Item.Content>
                        <Item.Actions class="flex-1 justify-end">
                          <InputGroup class="w-full max-w-[var(--container-sm)]">
                            <InputText
                              :model-value="dnssec.algorithm"
                              size="large"
                              class="flex-1 font-code"
                              aria-label="Algorithm"
                              readonly
                            />
                            <CopyButton
                              kind="transparent"
                              :value="dnssec.algorithm"
                              aria-label="Copy Algorithm"
                            />
                          </InputGroup>
                        </Item.Actions>
                      </Item>

                      <Item size="small" class="items-start">
                        <Item.Content>
                          <Item.Title>Digest Type</Item.Title>
                          <Item.Description>
                            Indicates the hash function used for the DNSSEC digest.
                          </Item.Description>
                        </Item.Content>
                        <Item.Actions class="flex-1 justify-end">
                          <InputGroup class="w-full max-w-[var(--container-sm)]">
                            <InputText
                              :model-value="dnssec.digestType"
                              size="large"
                              class="flex-1 font-code"
                              aria-label="Digest Type"
                              readonly
                            />
                            <CopyButton
                              kind="transparent"
                              :value="dnssec.digestType"
                              aria-label="Copy Digest Type"
                            />
                          </InputGroup>
                        </Item.Actions>
                      </Item>

                      <Item size="small" class="items-start">
                        <Item.Content>
                          <Item.Title>Digest</Item.Title>
                          <Item.Description>
                            Cryptographic hash of the public key for DNSSEC
                            validation. Provide this to your provider.
                          </Item.Description>
                        </Item.Content>
                        <Item.Actions class="flex-1 justify-end">
                          <InputGroup class="w-full max-w-[var(--container-sm)]">
                            <InputText
                              :model-value="dnssec.digest"
                              size="large"
                              class="flex-1 font-code"
                              aria-label="Digest"
                              readonly
                            />
                            <CopyButton
                              kind="transparent"
                              :value="dnssec.digest"
                              aria-label="Copy Digest"
                            />
                          </InputGroup>
                        </Item.Actions>
                      </Item>
                    </template>
                  </Item.List>
                </fieldset>
              </template>
              <template #footer>
                <div class="flex w-full items-center justify-end gap-[var(--spacing-sm)]">
                  <Button
                    label="Save"
                    kind="secondary"
                    size="medium"
                    :loading="savingDnssec"
                    :disabled="!dnssecDirty"
                    @click="saveDnssec"
                  />
                </div>
              </template>
            </CardBox>
          </form>

          <!-- Group: Status (own Save) -->
          <form
            class="flex flex-col gap-[var(--spacing-sm)]"
            aria-label="Status settings"
            novalidate
            @submit.prevent="saveStatus"
          >
            <p class="px-[var(--spacing-xs)] text-heading-xxs text-[var(--text-default)]">
              Status
            </p>
            <CardBox :padded="false">
              <template #content>
                <fieldset
                  class="m-0 flex min-w-0 flex-col border-0 p-0"
                  :disabled="savingStatus"
                >
                  <legend class="sr-only">Status</legend>
                  <Item.List>
                    <Item size="small">
                      <Item.Content>
                        <Item.Title>Active</Item.Title>
                        <Item.Description>
                          When active, the zone answers authoritative DNS queries
                          for the domain.
                        </Item.Description>
                      </Item.Content>
                      <Item.Actions class="flex-1 justify-end">
                        <Switch
                          v-model="statusForm.active"
                          aria-label="Active"
                          :disabled="savingStatus"
                        />
                      </Item.Actions>
                    </Item>
                  </Item.List>
                </fieldset>
              </template>
              <template #footer>
                <div class="flex w-full items-center justify-end gap-[var(--spacing-sm)]">
                  <Button
                    label="Save"
                    kind="secondary"
                    size="medium"
                    :loading="savingStatus"
                    :disabled="!statusDirty"
                    @click="saveStatus"
                  />
                </div>
              </template>
            </CardBox>
          </form>
        </div>
      </section>

      <!-- Records — a flush borderless Table; the create action is on the tab bar. -->
      <section v-else class="min-h-0 flex-1 overflow-auto p-[var(--spacing-md)]">
        <CardBox :padded="false">
          <template #content>
            <Table
              :data="records"
              :columns="recordColumns"
              row-key="id"
              enable-sorting
              paginated
              :page-size="8"
              :border="false"
            >
              <template #toolbar>
                <div class="flex w-full items-center gap-[var(--spacing-xs)]">
                  <Table.Search
                    size="large"
                    placeholder="Search records..."
                    class="flex-1"
                  />
                  <Table.RefreshButton />
                  <Table.Export />
                  <Table.ColumnSelector />
                </div>
              </template>

              <template #cell-name="{ value }">
                <span class="truncate text-label-sm text-[var(--text-default)]">{{ value }}</span>
              </template>

              <template #cell-id="{ value }">
                <span class="text-label-code-sm text-[var(--text-muted)]">{{ value }}</span>
              </template>

              <template #cell-type="{ value }">
                <Tag :label="value" severity="secondary" size="medium" />
              </template>

              <template #cell-value="{ value }">
                <div class="flex w-full min-w-0 items-center gap-[var(--spacing-xs)]">
                  <span class="min-w-0 truncate font-code text-label-code-sm text-[var(--text-default)]">
                    {{ value }}
                  </span>
                  <CopyButton
                    kind="outlined"
                    :value="value"
                    aria-label="Copy record value"
                    class="ml-auto shrink-0"
                    @click.stop
                  />
                </div>
              </template>

              <template #cell-policy="{ value }">
                <span class="text-body-sm text-[var(--text-muted)]">{{ policyLabel(value) }}</span>
              </template>

              <template #cell-weight="{ value }">
                <span class="text-body-sm text-[var(--text-muted)]">{{ value ?? "—" }}</span>
              </template>

              <template #cell-description="{ value }">
                <span class="truncate text-body-sm text-[var(--text-muted)]">{{ value || "—" }}</span>
              </template>

              <template #cell-actions="{ row }">
                <Dropdown
                  placement="bottom-end"
                  @select="(event, value) => onRecordAction(event, value, row)"
                >
                  <Dropdown.Trigger>
                    <IconButton
                      icon="pi pi-ellipsis-h"
                      kind="outlined"
                      size="small"
                      aria-label="Row actions"
                    />
                  </Dropdown.Trigger>
                  <Dropdown.Group>
                    <Dropdown.Option value="edit" label="Edit">
                      <template #left><i class="pi pi-pencil" aria-hidden="true" /></template>
                    </Dropdown.Option>
                  </Dropdown.Group>
                  <Dropdown.Group>
                    <Dropdown.Option value="delete" label="Delete">
                      <template #left><i class="pi pi-trash" aria-hidden="true" /></template>
                    </Dropdown.Option>
                  </Dropdown.Group>
                </Dropdown>
              </template>
            </Table>
          </template>
        </CardBox>
      </section>
    </main>

    <!-- Create Record — a right Drawer; on save the record is appended to the list. -->
    <CreateRecordDrawer
      v-model:open="recordDrawerOpen"
      :domain="domainForm.domain"
      @created="onRecordCreated"
    />
  </AppLayout>
</template>
